//WARNING This program has hardcoded use of TH1, if you are interested in doing this for MaCh3 you have to replace it for TH2Poly
//Furthmore "COLZ" option for draw
//TODO add T2Kstyle() or setStyle()

void loopdir(TString fname) {
   // example of script to loop on all the objects of a ROOT file directory
   // and print on Postscript all TH1 derived objects
   // This script uses the file generated by tutorial hsimple.C
   //Author: Rene Brun

   TFile *f1 = TFile::Open(fname);
   TIter next(f1->GetListOfKeys());
   TKey *key;
   TCanvas c1;
   c1.Print(Form("%s.pdf(",fname.Data()), "pdf");
   while ((key = (TKey*)next())) {
      TClass *cl = gROOT->GetClass(key->GetClassName());
      if (!cl->InheritsFrom("TH1")) continue;
      TH1 *h = (TH1*)key->ReadObj();
      h->Draw();
      c1.Print(Form("%s.pdf",fname.Data()), "pdf");
   }
   c1.Print(Form("%s.pdf)",fname.Data()), "pdf");
   
}
